### ISSUE TITLE
Reordered selections don't stick since 2.3.0

### ISSUE THREAD

**Issue by sentience** [Jako/SuperBoxSelect#11]
I recently upgraded SuperBoxSelect to 2.3.0 and then 2.3.1 on my site. Since doing so, the template variable I use it with no longer saves changes when I drag the selected items into a different order. If I delete an item from the list and then add a new one, the saved order of the new list does not match the assigned order either.

My site is running MODX 2.7.1.

I have reproduced this issue in both Safari and Chrome.

**Comment by sentience** [comment]
Here's a look at a reordered list (I dragged “Pull quote 2 (226)” from the bottom of the list up one slot, so that it was second from the last), and the resulting request form data that was sent when I clicked Save (note that the last two resource IDs were submitted in their original order).

![image](https://user-images.githubusercontent.com/89772/56730560-a3f75d00-679b-11e9-9606-608589104332.png)

**Comment by sentience** [comment]
And here's the DOM showing the hidden form fields not reordered to match the assigned order following the drag operation in the list:

![image](https://user-images.githubusercontent.com/89772/56731408-bffbfe00-679d-11e9-9975-8b1de49d1fbc.png)

**Comment by sentience** [comment]
I've confirmed that reverting to SuperBoxSelect 2.2.2 fixes this issue. It's difficult to debug the issue with the minified code included in the production package version, and I'm not sure how to set up the development version. My best guess is that something significant changed with the sortabjejs package version upgrade from 1.7.0. As far as I can tell, [the `onEnd` callback](https://github.com/Jako/SuperBoxSelect/blob/9dd6739ce9a808c48d0638673ef1dbee063c42ef/source/js/mgr/superboxselect.combo.templatevar.js#L74-L85) isn't being called at all (but again the minified code makes it difficult to be sure).

**Comment by Jako** [comment]
Will be fixed with the upcoming 2.3.2 release. If you want, you could download and test the next package from here: https://github.com/Jako/SuperBoxSelect/tree/master/_packages

**Comment by Jako** [comment]
2.3.2 is available.

**Comment by sentience** [comment]
@Jako I upgraded to 2.3.2 and the problem still exists.

Please let me know if you'd like to dig more deeply into diagnosing it again. Also happy to test the development version this time.

**Comment by Jako** [comment]
I narrowed it a bit: It works, when the page is reloaded. If a value is removed, the reordering does not work (the hidden inputs are not reordered).

**Comment by Jako** [comment]
Please check the 2.3.3 package in https://github.com/Jako/SuperBoxSelect/tree/master/_packages

**Comment by sentience** [comment]
I've checked 2.3.3 and I'm still not able successfully to reorder items. I am not removing any items from the list, I am just dragging the first item in the list to make it the second item in the list. This appears to work in the TV editing UI, but the change does not modify the database when you click Save, and when you reload the page the original order is restored in the TV UI.

By the way, there is also a visual difference in the TV editing UI between 2.2.2 and the 2.3.x versions:

2.2.2:
<img width="663" alt="CleanShot 2019-05-26 at 00 18 44@2x" src="https://user-images.githubusercontent.com/89772/58370636-4302a680-7f4c-11e9-8c31-05a4b7da2f28.png">

2.3.x:
<img width="663" alt="CleanShot 2019-05-26 at 00 17 01@2x" src="https://user-images.githubusercontent.com/89772/58370641-4a29b480-7f4c-11e9-820d-bc6ad99bb995.png">

**Comment by sentience** [comment]
Anything I can do to help move this towards a fix? If you can help me set up the development version on my machine, I could do a better job of isolating the problem.

**Comment by Jako** [comment]
Finally fixed with 2.3.4

**Comment by sentience** [comment]
Confirmed, this is fixed now. Thank you!

I would note that the [visual difference I highlighted above](https://github.com/Jako/SuperBoxSelect/issues/11#issuecomment-495922146), where each item in the list takes up the full width, is still present in 2.3.4. I'm not sure if that's a change you intended, or if you'd like to fix it.

**Comment by Jako** [comment]
That could be changed with a template variable setting: Stack Items -> No 

But for whatever reason, it does not work at the moment.

**Comment by Jako** [comment]
Thats fixed with 2.3.5.
