### ISSUE TITLE
Resources disappear

### ISSUE THREAD

**Issue by lottaar** [Jako/SuperBoxSelect#17]
Sometimes resources disappear från the tv. In my resource I had selected 13 (I think) resources from the SuperBoxSelect tv dropdown. After saving the resource and closing it and then reopening in, there were only 12 resources left. Then saving it again, closing it and then reopening it, there was only 11 resources left. So somehow selected resources vanish upon saving.

MODX 2.7.2-pl and SuperBoxSelect 2.3.7-pl.

**Comment by Jako** [comment]
Fixed with 2.3.8
