### ISSUE TITLE
Alert "The changes you made may not be saved"

### ISSUE THREAD

**Issue by EMDM45** [Jako/SuperBoxSelect#18]
I use modx with SuperBoxSelect. I have problem with it.
When i refresh resource page, browser sends me this message (alert):

> The changes you made may not be saved.

With disabled plugin (SuperBoxSelect) there is no problem.
The reason for this message is line 45 in elements/tv/input/superboxselect.class.php:

```$this->setPlaceholder('value', str_replace('||', ',', $value));```
 
This message is causing a problem to my client.
If it is possible, can you solve this problem?

**Comment by EMDM45** [comment]
Also, i would like to have full width of SuperBoxSelect field.

**Comment by Jako** [comment]
Your suggested patch did not really solve that issue. I had to dig deeper in the code.

It is solved by these lines: https://github.com/Jako/SuperBoxSelect/commit/d5c86e6d195a69855256817ca5fa48b6ee1a50ed#diff-ccfa8bd1d9dbbb801cb139525e8738cf

The patch is included in the upcoming version 2.4.0. It would be nice, if you could test the RC1 of that version: https://github.com/Jako/SuperBoxSelect/blob/master/_packages/superboxselect-2.4.0-rc1.transport.zip

**Comment by EMDM45** [comment]
In Log:
> [2020-03-22 11:40:57] (ERROR @ /web/core/components/superboxselect/processors/types/resources/getlist.class.php : 131) SELECT `modResource`.`id`, `modResource`.`pagetitle` FROM `modx_site_content` AS `modResource` WHERE  ( `modResource`.`parent` IN (27) AND  ( `modResource`.`deleted` = 0 AND `modResource`.`published` = 1 )  )

**Comment by Jako** [comment]
Do you have the debug mode of SuperBoxSelect enabled?

**Comment by EMDM45** [comment]
Yes, i do

**Comment by Jako** [comment]
Then the query is logged.

**Comment by EMDM45** [comment]
> The patch is included in the upcoming version 2.4.0. It would be nice, if you could test the RC1 of that version: https://github.com/Jako/SuperBoxSelect/blob/master/_packages/superboxselect-2.4.0-rc1.transport.zip

it solves my problem. Thank you.
Could you stretch field to full width of TVs-tab? (width:100%)

**Comment by Jako** [comment]
Changing the width is not that easy because of the manager. I currently have no good solution for this.
