### ISSUE TITLE
Feature Request: Sort order for display

### ISSUE THREAD

**Issue by rdegler** [Jako/SuperBoxSelect#22]
It would help to have a sortby choice (ie pagetitle, pubdate, createdate, etc)  It appears to be  using menu index, but other other options would improve the usability for the content editor. 

Thanks,
Roy

**Comment by Jako** [comment]
The dropdown list is ordered by pagetitle per default. Maybe this could be changed somehow to something configurable.

**Comment by Jako** [comment]
It is configurable with 3.0.6
