### ISSUE TITLE
Limit to Related Context is not working

### ISSUE THREAD

**Issue by jdaehne** [Jako/SuperBoxSelect#23]
The setting "Limit to Related Context" is not working. If i set this setting to true - i still get all the resources of both contexts. I do not have any additional settings.

**Comment by jdaehne** [comment]
I tried to inspect the issue and can not realy get this, but the variable `$limitRelatedContext` in `components/superboxselect/processors/types/resources/getlist.class.php` is always false. No matter what i select.

`$this->getProperty('limitRelatedContext')` seems to be always "false".

**Comment by Jako** [comment]
It is fixed with 8d32ed6e33ce8eacbe54a65ff59b222d9c56ed9e. The twig template does not like `===` instead of `==`.
