### ISSUE TITLE
Feature Request-  Snippet to output resource IDs as links

### ISSUE THREAD

**Issue by rdegler** [Jako/SuperBoxSelect#28]
It would be nice to have a snippet like toLinks from tagLister.  Having to generate either a getResources or pdoResouces call to convert stored IDs to links is not the most efficient solution.  I am sure a php level snippet would reduce the drag on system resources and be faster.

Thanks
Roy

**Comment by Jako** [comment]
I don't think that this has to be part of SuperBoxSelect. It is too specific.
