### ISSUE TITLE
Setting page size to 0 does not disable pagination

### ISSUE THREAD

**Issue by sentience** [Jako/SuperBoxSelect#6]
The description of the Page Size property suggests that setting it to 0 will disable the pagination and simply display all available resources in the drop-down list.

In practice, I’m finding that setting it to 0 causes it to default to a page size of 10.

This appears to be a bug in the JavaScript in superboxselect.render.tpl:

```
                pageSize: ({$params.pageSize * 1}) || 10,
```

When `$params.pageSize` is `0`, this will set `pageSize` to `10`, because the `||` operator considers `0` to be false.

**Comment by Jako** [comment]
Fixed with https://github.com/Jako/SuperBoxSelect/commit/66356855e611c1488b7389978d58f68114f4d23f#diff-524464935f80143eb1d1fb4f0c7f5cb5
